on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: development
      url: http://localhost:8080/game2048
    steps:
      - name: Download war
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: /usr/local/tomcat/webapps

  # deploy:
  #   runs-on: self-hosted
  #   needs: [ package ]
  #   dependencies:
  #     - package
  #   when: manual
  #   environment:
  #     name: test
  #     action: start
  #     url: http://localhost:8080/game2048
  #     on_stop: stop
  #   script:
  #     - docker rm --force game2048
  #     - docker image rm --force game2048
  #     - echo -e 'FROM tomcat:9-jdk17-openjdk-slim\nCOPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
  #     - docker run --rm -d --name game2048 -p 8080:8080 game2048

  # stop:
  #   stage: deploy
  #   tags:
  #     - shell
  #   when: manual
  #   environment:
  #     name: test
  #     action: stop
  #     url: http://localhost:8080/game2048
  #   script:
  #     - docker rm --force game2048
  #     - docker image rm --force game2048