on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

  build:
    runs-on: self-hosted
    needs: [ checkout ]
    steps:
      - name: Compile
        run: mvn compile

  test:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Run tests
        run: mvn test
      - name: Publish test coverage results
        uses: actions/upload-artifact@v3
        with:
          name: 2048-game-jcoco
          path: target/site/jacoco/*
      - name: Publish test report
        uses: actions/upload-artifact@v3
        with:
          name: 2048-game-surefire
          path: target/surefire-reports/*

  package:
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Package
        run: mvn package
      - name: Publish war
        uses: actions/upload-artifact@v3
        with:
          name: 2048-game-war
          path: target/*.war

  deploy:
    runs-on: self-hosted
    needs: [ package, test ]
    environment:
      name: development
      url: http://localhost:8081/game2048
    steps:
      - name: Download war
        uses: actions/download-artifact@v3
        with:
          name: 2048-game-war
          path: /usr/local/tomcat/webapps